fail_fast: false

exclude: |
  (?x)^(
    .venv/
    .tox/
  )

repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  # Protect secrets using Gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.29.1
    hooks:
      - id: gitleaks
  # uv lockfile management
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.13
    hooks:
      - id: uv-lock
  # Base hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=49999]
      - id: check-ast
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  # Add trailing commas to calls and literals.
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma
  # Opinionated markdown formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        language: python
        additional_dependencies:
          - mdformat-mkdocs==5.1.1
  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.46.0
    hooks:
      - id: markdownlint
        types: [file]
        files: .(md)$
        args: [--disable, MD013]
  # Spell check
  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
  # Lint & format with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check
        args: [--config=pyproject.toml, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--config=pyproject.toml]
  # Validate pyproject.toml
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
