---
exclude: |
  (?x)^(
    .venv/
  )

repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  # Protect secrets using Gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.29.1
    hooks:
      - id: gitleaks
  # Supported base hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=49999]
      - id: check-ast
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  # Add trailing commas to calls and literals.
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma
  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.46.0
    hooks:
      - id: markdownlint
        types: [file]
        files: .(md)$
        args: [--disable, MD013]
  # Spell check
  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
  # Lint & format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check
        args: [--config=pyproject.toml, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--config=pyproject.toml]
